name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: lua5.3 pandoc libreoffice

      - name: Render files
        run: ./render.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: datasheets
          path: output/
